/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 24ec9089a68a83802d2e84de22ca17d9)
interface __BaseEnv_Env {
	AUTH_DB: D1Database;
	API_RATE_LIMITER: RateLimit;
	AUTH_RATE_LIMITER: RateLimit;
	ASSETS: Fetcher;
	ALLOWED_ORIGINS: "https://ilovefood.imstevelin.com";
	OPENPOINT_GID: string;
	OPENPOINT_MID: string;
	OPENPOINT_VCODE: string;
	OPENPOINT_IMAP_MASTER_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS" | "OPENPOINT_GID" | "OPENPOINT_MID" | "OPENPOINT_VCODE" | "OPENPOINT_IMAP_MASTER_KEY">> {}
}
